name: hibis_academy
description: Hibis academy website
version: 0.0.2
environment:
  sdk: '>=1.24.2 <2.0.0'
dependencies:
  angular_router: ^1.0.2
  angular: ^4.0.0
  angular_components: ^0.7.1
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.3
transformers:
- angular:
    entry_points: web/signup.dart
- dart_to_js_script_rewriter
web:
  compiler:
    debug: dartdevc
    #release: dartdevc
