name: hibis_academy
description: Hibis academy website
version: 0.0.2
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_router: ^2.0.0-alpha+21

dev_dependencies:
  build_runner: ^1.2.0
  build_web_compilers: ^1.2.0
